removeAnvilLimit = true
allowAllEnchantmentCombinations = true
allowAnyEnchantOnAnyItem = false
useGlobalEnchantCap = true
globalEnchantCap = 20
protectionCap = 4
protectionFireCap = 5
protectionBlastCap = 5
protectionProjectileCap = 5
respirationCap = 4
thornsCap = 3
frostWalkerCap = 2
soulSpeedCap = 3
depthStriderCap = 3
featherFallingCap = 5
smiteCap = 5
sharpnessCap = 6
baneOfArthropodsCap = 5
knockbackCap = 2
fireAspectCap = 2
lootingCap = 4
sweepingCap = 3
efficiencyCap = 4
fortuneCap = 4
powerCap = 5
punchCap = 2
lureCap = 4
luckOfTheSeaCap = 4
impalingCap = 5
loyaltyCap = 3
quickChargeCap = 3
piercingCap = 5
unbreakingCap = 3
